# Generated by Django 2.0.7 on 2018-09-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kirrurl',
            name='shortcode',
            field=models.CharField(default='johan se default', max_length=15),
            preserve_default=False,
        ),
    ]
